# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(526, 510)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 471, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.Meters = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.Meters.setObjectName("Meters")
        self.gridLayout.addWidget(self.Meters, 1, 0, 1, 1)
        self.Kilometers = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.Kilometers.setObjectName("Kilometers")
        self.gridLayout.addWidget(self.Kilometers, 2, 0, 1, 1)
        self.Centimeters = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.Centimeters.setObjectName("Centimeters")
        self.gridLayout.addWidget(self.Centimeters, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.Cals = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.Cals.setObjectName("Cals")
        self.gridLayout.addWidget(self.Cals, 0, 2, 1, 1)
        self.Foots = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.Foots.setObjectName("Foots")
        self.gridLayout.addWidget(self.Foots, 1, 2, 1, 1)
        self.Miles = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.Miles.setObjectName("Miles")
        self.gridLayout.addWidget(self.Miles, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Centymetry na cale:"))
        self.label_2.setText(_translate("Dialog", "Metry na stopy:"))
        self.label_3.setText(_translate("Dialog", "Kilometry na mile:"))
